# pr-validator.yml
# Validates Laravel API pull requests by running migrations + tests

trigger: none

pr:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  PHP_VERSION: "8.2"

steps:
  - checkout: self
    fetchDepth: 1

  # Cache composer downloads to speed up subsequent runs
  - task: Cache@2
    inputs:
      key: 'composer | "$(Agent.OS)" | composer.lock'
      restoreKeys: |
        composer | "$(Agent.OS)"
      path: $(Pipeline.Workspace)/.composer-cache
    displayName: Cache Composer

  - script: |
      set -euo pipefail

      sudo apt-get update

      # Install PHP + common extensions used by Laravel
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository ppa:ondrej/php -y
      sudo apt-get update

      sudo apt-get install -y \
        php${PHP_VERSION} \
        php${PHP_VERSION}-cli \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-sqlite3 \
        php${PHP_VERSION}-zip

      sudo update-alternatives --set php /usr/bin/php${PHP_VERSION}

      php -v

      # Ensure Composer exists
      if ! command -v composer >/dev/null 2>&1; then
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer
        rm composer-setup.php
      fi

      composer -V
    displayName: Install PHP + extensions + Composer

  - script: |
      set -euo pipefail

      # Use pipeline workspace as composer cache
      export COMPOSER_CACHE_DIR="$(Pipeline.Workspace)/.composer-cache"

      composer install \
        --no-interaction \
        --no-progress \
        --prefer-dist
    displayName: Composer install

  - script: |
      set -euo pipefail

      # Prepare env for testing
      cp .env.example .env

      php artisan key:generate --ansi

      # Create sqlite database file
      mkdir -p database
      touch database/database.sqlite

      # Export env vars for this step + tests
      export APP_ENV=testing
      export APP_DEBUG=false
      export CACHE_DRIVER=array
      export SESSION_DRIVER=array
      export QUEUE_CONNECTION=sync

      export DB_CONNECTION=sqlite
      export DB_DATABASE="$(System.DefaultWorkingDirectory)/database/database.sqlite"

      # Run migrations (needed for RefreshDatabase tests)
      php artisan migrate --force --no-interaction

      # Run tests
      php artisan test --ansi
    displayName: Migrate + run tests (SQLite)
